TERMUX_PKG_HOMEPAGE=https://mate-session-manager.mate-desktop.dev/
TERMUX_PKG_DESCRIPTION="mate-session contains the MATE session manager, as well as a configuration program to choose applications starting on login."
TERMUX_PKG_LICENSE="GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.27.0
TERMUX_PKG_SRCURL=https://github.com/mate-desktop/mate-session-manager/releases/download/v${TERMUX_PKG_VERSION}/mate-session-manager-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=987aa024cd37116e330a309fe52def038e5f1d26af1b566675399dda6911aae1
TERMUX_PKG_DEPENDS="dbus, dbus-glib, gdk-pixbuf, glib, gtk3, libcairo, libepoxy, libice, libsm, libx11, libxau, libxcomposite, libxext, libxrender, libxtst, opengl"
TERMUX_PKG_AUTO_UPDATE=true
