#!/usr/bin/env python3

# The MIT License (MIT)

# Copyright (c) 2022 Aditya Alok <alok@termux.dev>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import json
import sys

from os.path import getsize as getfilesize
from requests import get as requests_get
from time import sleep


def get_repology_data(last_project, project):
    url = f"https://repology.org/api/v1"
    if project != "":
        last_project = project

    url = f"{url}/projects/{last_project}{'/' if last_project != '' else ''}?inrepo=termux&outdated=1&families_newest=2-"

    repology_data = requests_get(url, timeout=60, headers={'User-Agent': 'Termux update checker 1.0 (github.com/termux/termux-packages)'}).json()
    # NOTE: We are using `families_newest=2-` so that api will return a
    # package as outdated if it is so in 2 or more
    # repo family. This helps us avoid false positives.

    return repology_data


def get_outdated_packages(project):
    termux_outdated_packages = {}
    last_project = ""

    while True:
        # sleep to ensure we do not flood repology with requests
        sleep(1)
        repology_data = get_repology_data(last_project, project)
        project = "" # clear to not loop again
        repology_data_keys = sorted(repology_data.keys())
        first_project = repology_data_keys[0]
        last_project = repology_data_keys[-1]
        # last_project is used to query next set of packages
        print(f"{len(repology_data)}: {first_project} {last_project}")
        # Quoting repology documentation: "You may iterate through
        # all projects by using the last project name in the next request"
        # For more info, visit https://repology.org/api
        # NOTE: next response to request will include the last_project given.
        if len(repology_data) <= 1:
            # Break the loop now. Since api returned only one package, it
            # must be the last_project, which was already included in previous iteration.
            break

        for package_name, package_data in repology_data.items():
            for repo_data in package_data:
                if repo_data["repo"] == "termux":
                    package_name = repo_data["visiblename"]
                    break
            if package_name in termux_outdated_packages:
                # Skip if package is already in the dict.
                continue
            newest_stable = None
            newest_devel = None
            for repo_data in package_data:
                if repo_data.get("status", "") == "newest":
                    newest_stable = repo_data["version"]
                    # If we found stable version, break the loop.
                    break
                elif repo_data.get("status", "") == "devel":
                    # Do not break the loop if we found devel version as there may be stable version later.
                    newest_devel = repo_data["version"]

            if newest_stable:
                termux_outdated_packages[package_name] = newest_stable
            elif newest_devel:
                termux_outdated_packages[package_name] = newest_devel
            else:
                # If we don't find any version, skip the package.
                continue

    return dict(sorted(termux_outdated_packages.items()))


if __name__ == "__main__":
    try:
        output_file = sys.argv[1]
    except IndexError:
        sys.exit("ERROR: Please provide an output file")

    try:
        project = sys.argv[2]
    except IndexError:
        project = ""

    try:
        file_size = getfilesize(output_file)
    except Exception:
        file_size = -1

    if file_size > 3: # {} is size 3
        print(f"INFO: Reusing {output_file} (size={file_size})")
        sys.exit()

    with open(output_file, "w") as f:
        try:
            json.dump(get_outdated_packages(project), f)
        except Exception as error:
            print(f"ERROR: {type(error).__name__}", file=sys.stderr)
            print(error, file=sys.stderr)
            print(f"WARN: The 'dump-repology-data' script was unsuccessful, so an empty json is being placed in {output_file}", file=sys.stderr)
            print("{}", file=f)
            sys.exit()

    file_size = getfilesize(output_file)
    print(f"INFO: 'dump-repology-data' successfully dumped to {output_file} (size={file_size})")
