TERMUX_PKG_HOMEPAGE=https://libclc.llvm.org
TERMUX_PKG_DESCRIPTION="Open source implementation of OpenCL 1.1 library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="19.1.7"
TERMUX_PKG_SRCURL=https://github.com/llvm/llvm-project/releases/download/llvmorg-${TERMUX_PKG_VERSION}/libclc-${TERMUX_PKG_VERSION}.src.tar.xz
TERMUX_PKG_SHA256=77e2d71f5cea1d0b1014ba88186299d1a0848eb3dc20948baae649db9e7641cb
TERMUX_PKG_DEPENDS="libc++, libllvm"
TERMUX_PKG_BUILD_DEPENDS="libllvm-static"
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DLIBCLC_CUSTOM_LLVM_TOOLS_BINARY_DIR=${TERMUX_STANDALONE_TOOLCHAIN}/bin
"
