TERMUX_PKG_HOMEPAGE=https://github.com/KhronosGroup/SPIRV-LLVM-Translator
TERMUX_PKG_DESCRIPTION="SPIR-V LLVM Translator"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
_LLVM_VERSION=$(. $TERMUX_SCRIPTDIR/packages/libllvm/build.sh; echo "${TERMUX_PKG_VERSION}")
TERMUX_PKG_VERSION="1"
TERMUX_PKG_SRCURL=git+https://github.com/KhronosGroup/SPIRV-LLVM-Translator
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BUILD_DEPENDS="libllvm-static, libpolly, llvm-tools, llvmgold, mlir, spirv-headers, spirv-tools"
TERMUX_PKG_NO_STATICSPLIT=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBASE_LLVM_VERSION=${_LLVM_VERSION}
-DLLVM_EXTERNAL_SPIRV_HEADERS_SOURCE_DIR=${TERMUX_PREFIX}
"
TERMUX_PKG_EXTRA_MAKE_ARGS="
llvm-spirv
"
