TERMUX_PKG_HOMEPAGE=https://libmateweather.mate-desktop.dev/
TERMUX_PKG_DESCRIPTION="libmateweather is a libgnomeweather fork."
TERMUX_PKG_LICENSE="LGPL-2.1, GPL-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION=1.27.0
TERMUX_PKG_SRCURL=https://github.com/mate-desktop/libmateweather/releases/download/v${TERMUX_PKG_VERSION}/libmateweather-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=c4d3b47e327e2d1196e933695e930167e15b4f7e2f271e98bc708bcf0a809926
TERMUX_PKG_DEPENDS="atk, gdk-pixbuf, glib, gtk3, harfbuzz, libcairo, libsoup, libxml2, pango, zlib"
TERMUX_PKG_AUTO_UPDATE=true
