TERMUX_PKG_HOMEPAGE=https://github.com/WebAssembly/wabt
TERMUX_PKG_DESCRIPTION="The WebAssembly Binary Toolkit"
TERMUX_PKG_LICENSE="Apache-2.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.0.34"
TERMUX_PKG_SRCURL=https://github.com/WebAssembly/wabt/releases/download/${TERMUX_PKG_VERSION}/wabt-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_SHA256=049fa39dedac7fbdba661be77d719223807ba0670f5da79e75aa85d88fedc8a9
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_DEPENDS="libc++"
UTERMUX_PKG_EXTRA_CONFIGURE_ARGS="
-DBUILD_TESTS=OFF
"
