name: test-after-build
description: Test using Android Emulator
runs:
  using: "composite"
  steps:
    - name: Get *.deb files
      uses: actions/download-artifact@v6
      with:
        path: ./
        pattern: debs-*
    - name: Extract *.deb files
      shell: bash
      run: |
        for archive in debs-*/debs-${{ matrix.target_arch }}-${{ github.sha }}.tar; do
          tar -xvf "$archive"
        done
    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    - name: Download Termux APK (Debug)
      shell: bash
      run: |
        while true; do
          if curl -vL \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            --retry 3 \
            https://api.github.com/repos/termux/termux-app/releases/latest \
            -o response.json; then
            break
          fi
          sleep 3
        done
        TERMUX_APK_URL=$(grep browser_download_url response.json | sed -e 's|.*: ||' -e 's|"||g')
        case "${{ matrix.target_arch }}" in
        aarch64) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep arm64) ;;
        arm) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep armeabi) ;;
        i686) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep x86 | grep -v x86_64) ;;
        x86_64) TERMUX_APK_URL=$(echo "$TERMUX_APK_URL" | grep x86_64) ;;
        *) echo "ERROR: $*" && exit 1 ;;
        esac
        echo | xargs -t curl -vL \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2026-03-10" \
          $TERMUX_APK_URL \
          -o termux-${{ matrix.target_arch }}.apk
    - name: Disable console authentication
      # TODO explore later
      # https://developer.android.com/studio/run/emulator-console#console-session
      shell: bash
      run: |
        > ~/.emulator_console_auth_token
    - name: Test with Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api }} # 24-30
        arch: ${{ matrix.arch }} # arm64-v8a, x86, x86_64
        target: ${{ matrix.image }} # default, google_apis
        cores: 4
        ram-size: 2048M
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        enable-hw-keyboard: true
        script: |
          # proposed bootstrapping script
          #./scripts/test-runner-ci.sh

          pwd; ls -l; rm -f ok

          adb shell getprop ro.product.cpu.abilist

          for i in $(seq -w 1 100); do if test -f ok; then break; fi; adb logcat >logcat${i}.txt; done &
          # 180s = 3min, 6h = 360min = 120 * 3min
          for i in $(seq -w 1 116); do if test -f ok; then break; fi; if ! adb shell test -f /system/bin/screenrecord; then echo "WARN: screenrecord is non existant, skipping recording"; break; fi; adb shell screenrecord --verbose --time-limit 180 /sdcard/sr${i}.mp4; sync; adb pull /sdcard/sr${i}.mp4; adb shell rm /sdcard/sr${i}.mp4; done &

          tar -cf payload.tar.gz -C ../termux-packages .git repo.json scripts/properties.sh scripts/setup-termux.sh
          tar -cf packages.tar.gz -C ../termux-packages debs/*.deb

          adb install -g termux-${{ matrix.target_arch }}.apk
          adb shell pm path com.termux
          adb shell am start -n com.termux/com.termux.app.TermuxActivity
          sleep 30
          #adb shell pm grant com.termux android.permission.READ_EXTERNAL_STORAGE
          #adb shell pm grant com.termux android.permission.WRITE_EXTERNAL_STORAGE
          adb shell input text "termux-setup-storage%s\&\&%ssleep%s1"
          adb shell input keyevent KEYCODE_ENTER
          adb shell input keyevent KEYCODE_ENTER
          sleep 1

          adb shell id
          adb shell run-as com.termux id
          adb shell input text "id\%s\|%stee%sid\.txt%s\&\&%ssleep%s1"
          adb shell input keyevent KEYCODE_ENTER
          sleep 1
          adb shell 'run-as com.termux cat /data/data/com.termux/files/home/id.txt || true'

          adb shell df -h /data/local/tmp
          adb shell rm -fr /data/local/tmp/tmp
          adb shell mkdir -p /data/local/tmp/tmp
          adb push payload.tar.gz /data/local/tmp/tmp/payload.tar.gz
          adb push packages.tar.gz /data/local/tmp/tmp/packages.tar.gz
          adb shell df -h /data/local/tmp
          adb shell ls -l /data/local/tmp/tmp
          adb shell run-as com.termux ls -l /data/local/tmp/tmp
          adb shell input text "ls%s\-l%s\/data\/local\/tmp\/tmp%s\|%stee%stmp\.txt%s\&\&%ssleep%s1"
          adb shell input keyevent KEYCODE_ENTER
          sleep 1
          adb shell 'run-as com.termux cat /data/data/com.termux/files/home/tmp.txt || true'

          adb shell run-as com.termux pwd
          adb shell run-as com.termux ls -l
          adb shell run-as com.termux ls -l /data/data/com.termux
          adb shell run-as com.termux ls -l /data/data/com.termux/files
          adb shell run-as com.termux ls -l /data/data/com.termux/files/home
          adb shell 'run-as com.termux ls -l /data/data/com.termux/files/home/storage || true'
          adb shell 'run-as com.termux ls -l /data/data/com.termux/files/home/storage/shared || true'
          adb shell run-as com.termux ls -l /data/data/com.termux/files/usr

          adb shell run-as com.termux mkdir -p /data/data/com.termux/files/home/termux-packages
          adb shell run-as com.termux tar -xof /data/local/tmp/tmp/payload.tar.gz -C /data/data/com.termux/files/home/termux-packages
          adb shell run-as com.termux tar -xof /data/local/tmp/tmp/packages.tar.gz -C /data/data/com.termux/files/home/termux-packages

          adb shell input text "watch%sps%sax%s-H"
          adb shell input keyevent KEYCODE_ENTER
          sleep 1
          adb shell run-as com.termux ps

          adb shell run-as com.termux rm -f /data/data/com.termux/files/usr/etc/termux/chosen_mirrors
          adb shell 'run-as com.termux env PATH=/data/data/com.termux/files/usr/bin bash -c "yes | pkg install termux-tools"'
          adb shell run-as com.termux ln -sv ../mirrors/default /data/data/com.termux/files/usr/etc/termux/chosen_mirrors

          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages/scripts
          adb shell run-as com.termux chmod +x /data/data/com.termux/files/home/termux-packages/scripts/setup-termux.sh
          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages/scripts
          #adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin bash /data/data/com.termux/files/home/termux-packages/scripts/setup-termux.sh
          #adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin pkg install xxd jq git -y
          adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin pkg install git -y
          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages
          adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin git -C /data/data/com.termux/files/home/termux-packages restore .
          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages
          adb shell run-as com.termux ls -l /data/data/com.termux/files/home/termux-packages/debs

          adb shell run-as com.termux env PATH=/data/data/com.termux/files/usr/bin pkg install x11-repo -y
          adb shell 'run-as com.termux env PATH=/data/data/com.termux/files/usr/bin bash -c "cd /data/data/com.termux/files/home/termux-packages/debs; yes | pkg install ./*.deb"'
          adb shell "run-as com.termux env PATH=/data/data/com.termux/files/usr/bin HOME=/data/data/com.termux/files/home bash -c \"cd ~/termux-packages; ./scripts/test-runner.sh $PACKAGES\"" || touch error

          touch ok
          adb shell "while true; do if ! pidof screenrecord >/dev/null; then pidof logcat; pkill -n logcat; break; fi; sleep 1; done"
          if test -f error; then echo "ERROR: Test failed!"; exit 88; fi
    - name: Upload logs and videos
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: testafterbuild-${{ matrix.target_arch }}-${{ matrix.api }}-${{ matrix.image }}-${{ github.sha }}
        path: |
          logcat*.txt
          sr*.mp4
