TERMUX_PKG_HOMEPAGE=https://julialang.org/
TERMUX_PKG_DESCRIPTION="The Julia Programming Language"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="1.11.2"
UTERMUX_PKG_SRCURL=https://github.com/JuliaLang/julia/releases/download/v${TERMUX_PKG_VERSION}/julia-${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SRCURL=https://github.com/JuliaLang/julia/releases/download/v${TERMUX_PKG_VERSION}/julia-${TERMUX_PKG_VERSION}-full.tar.gz
UTERMUX_PKG_SHA256=a7365b969944f27df0d8563716ca9769e07f3f77b9f9fbb48bcd114ddf752ca4
TERMUX_PKG_SHA256=a7365b969944f27df0d8563716ca9769e07f3f77b9f9fbb48bcd114ddf752ca4
UTERMUX_PKG_DEPENDS="libc++, libllvm, libuv, p7zip"
TERMUX_PKG_DEPENDS="libc++"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_MAKE_PROCESSES=1
UTERMUX_PKG_EXTRA_MAKE_ARGS="
USE_SYSTEM_CSL=1
USE_SYSTEM_LLVM=1
USE_SYSTEM_LIBUNWIND=1
DISABLE_LIBUNWIND=0
USE_SYSTEM_PCRE=1
USE_SYSTEM_LIBM=1
USE_SYSTEM_OPENLIBM=1
UNTRUSTED_SYSTEM_LIBM=0
USE_SYSTEM_DSFMT=1
USE_SYSTEM_LIBBLASTRAMPOLINE=1
USE_SYSTEM_BLAS=0
USE_SYSTEM_LAPACK=1
USE_SYSTEM_GMP=1
USE_SYSTEM_MPFR=1
USE_SYSTEM_LIBSUITESPARSE=0
USE_SYSTEM_LIBUV=1
USE_SYSTEM_UTF8PROC=1
USE_SYSTEM_MBEDTLS=1
USE_SYSTEM_LIBSSH2=1
USE_SYSTEM_NGHTTP2=1
USE_SYSTEM_CURL=1
USE_SYSTEM_LIBGIT2=1
USE_SYSTEM_PATCHELF=1
USE_SYSTEM_LIBWHICH=1
USE_SYSTEM_ZLIB=1
USE_SYSTEM_P7ZIP=1
USE_SYSTEM_LLD=1
LLVM_CONFIG=${TERMUX_PREFIX}/bin/llvm-config
LOCALBASE=${TERMUX_PREFIX}
7Z_PATH=${TERMUX_PREFIX}/bin/7z
"

termux_step_pre_configure() {
	termux_setup_cmake

	if [[ "${TERMUX_ARCH}" == "arm" ]]; then
		TERMUX_PKG_EXTRA_MAKE_ARGS+=" XCHOST=armv7a-linux-androideabi"
	else
		TERMUX_PKG_EXTRA_MAKE_ARGS+=" XCHOST=${TERMUX_ARCH}-linux-android"
	fi
	TERMUX_PKG_EXTRA_MAKE_ARGS+=" VERBOSE=1"
	CFLAGS+=" -v"
	LDFLAGS+=" -Wl,--undefined-version"
}
