name: Vagrant

on:
  push:
    branches:
    - master
    - dev
    - 'dev/**'
    paths:
    - 'scripts/Vagrantfile'
  pull_request:
    paths:
    - 'scripts/Vagrantfile'

permissions: {} # none

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Run "vagrant up" in scripts directory
      run: |
        pushd scripts
        vagrant up
        popd
    - name: git status && git diff
      run: git status && git diff
